const number1 = 8;
const number2 = 24;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 55;
const payment = 31;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const tests = 100;
const assignments = 77;
const final = 98;
const grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Kitlong';
const lastName = 'Lai';
const fullName = firstName + ' ' + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 9;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 12;
const isSparta = (numberOfSoldiers === 300);
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += ' is the GOAT';
console.log(typeof nickname);
console.log(nickname);
console.log('test');
